export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    me: '/auth/me',
    permissions: '/auth/permissions',
    register: '/auth/register',
  },
  users: {
    list: '/users',
    detail: (id: string) => `/users/${id}`,
    create: '/users',
    update: (id: string) => `/users/${id}`,
    delete: (id: string) => `/users/${id}`,
  },
  customers: {
    list: '/customers',
    detail: (id: string) => `/customers/${id}`,
    create: '/customers',
    update: (id: string) => `/customers/${id}`,
    delete: (id: string) => `/customers/${id}`,
    search: '/customers/search',
  },
  jobs: {
    list: '/jobs',
    detail: (id: string) => `/jobs/${id}`,
    create: '/jobs',
    update: (id: string) => `/jobs/${id}`,
    delete: (id: string) => `/jobs/${id}`,
    status: (id: string) => `/jobs/${id}/status`,
    assign: (id: string) => `/jobs/${id}/assign`,
    board: '/jobs/board',
  },
  quotations: {
    list: '/quotations',
    detail: (id: string) => `/quotations/${id}`,
    create: '/quotations',
    update: (id: string) => `/quotations/${id}`,
    approve: (id: string) => `/quotations/${id}/approve`,
    reject: (id: string) => `/quotations/${id}/reject`,
    pdf: (id: string) => `/quotations/${id}/pdf`,
  },
  purchaseOrders: {
    list: '/purchase-orders',
    detail: (id: string) => `/purchase-orders/${id}`,
    create: '/purchase-orders',
    update: (id: string) => `/purchase-orders/${id}`,
    approve: (id: string) => `/purchase-orders/${id}/approve`,
  },
  products: {
    list: '/products',
    detail: (id: string) => `/products/${id}`,
    create: '/products',
    update: (id: string) => `/products/${id}`,
    delete: (id: string) => `/products/${id}`,
    adjustStock: (id: string) => `/products/${id}/adjust-stock`,
    movements: (id: string) => `/products/${id}/movements`,
    lowStock: '/products/low-stock',
  },
  payments: {
    list: '/payments',
    detail: (id: string) => `/payments/${id}`,
    create: '/payments',
    verify: (id: string) => `/payments/${id}/verify`,
    invoice: (id: string) => `/payments/${id}/invoice`,
  },
  dashboard: {
    stats: '/dashboard/stats',
    revenue: '/dashboard/revenue',
    activities: '/dashboard/activities',
    reports: '/reports/generate',
    exportReport: '/reports/export',
  },
  documents: {
    list: '/documents',
    detail: (id: string) => `/documents/${id}`,
    upload: '/documents/upload',
    delete: (id: string) => `/documents/${id}`,
    share: (id: string) => `/documents/${id}/share`,
  },
  email: {
    templates: '/email/templates',
    createTemplate: '/email/templates',
    send: '/email/send',
    sendBulk: '/email/send-bulk',
    logs: '/email/logs',
  },
  batch: {
    jobs: '/batch/jobs',
    create: '/batch/jobs',
    trigger: (id: string) => `/batch/jobs/${id}/trigger`,
    history: (id: string) => `/batch/jobs/${id}/history`,
  },
  iot: {
    devices: '/iot/devices',
    register: '/iot/devices',
    location: (id: string) => `/iot/devices/${id}/location`,
    history: (id: string) => `/iot/devices/${id}/history`,
    sensors: (id: string) => `/iot/devices/${id}/sensors`,
  },
  wos: {
    orders: '/wos/orders',
    detail: (id: string) => `/wos/orders/${id}`,
    create: '/wos/orders',
    status: (id: string) => `/wos/orders/${id}/status`,
    cancel: (id: string) => `/wos/orders/${id}/cancel`,
  },
};
