export const API_ENDPOINTS = {
  auth: {
    login: '/api/v1/auth/login',
    logout: '/api/v1/auth/logout',
    refresh: '/api/v1/auth/refresh',
    forgotPassword: '/api/v1/auth/forgot-password',
    resetPassword: '/api/v1/auth/reset-password',
    me: '/api/v1/auth/me',
    permissions: '/api/v1/auth/permissions',
  },
  users: {
    list: '/api/users',
    detail: (id: string) => `/api/users/${id}`,
    create: '/api/users',
    update: (id: string) => `/api/users/${id}`,
    delete: (id: string) => `/api/users/${id}`,
  },
  customers: {
    list: '/api/customers',
    detail: (id: string) => `/api/customers/${id}`,
    create: '/api/customers',
    update: (id: string) => `/api/customers/${id}`,
    delete: (id: string) => `/api/customers/${id}`,
    search: '/api/customers/search',
  },
  jobs: {
    list: '/api/jobs',
    detail: (id: string) => `/api/jobs/${id}`,
    create: '/api/jobs',
    update: (id: string) => `/api/jobs/${id}`,
    delete: (id: string) => `/api/jobs/${id}`,
    status: (id: string) => `/api/jobs/${id}/status`,
    assign: (id: string) => `/api/jobs/${id}/assign`,
    board: '/api/jobs/board',
  },
  quotations: {
    list: '/api/quotations',
    detail: (id: string) => `/api/quotations/${id}`,
    create: '/api/quotations',
    update: (id: string) => `/api/quotations/${id}`,
    approve: (id: string) => `/api/quotations/${id}/approve`,
    reject: (id: string) => `/api/quotations/${id}/reject`,
    pdf: (id: string) => `/api/quotations/${id}/pdf`,
  },
  purchaseOrders: {
    list: '/api/purchase-orders',
    detail: (id: string) => `/api/purchase-orders/${id}`,
    create: '/api/purchase-orders',
    update: (id: string) => `/api/purchase-orders/${id}`,
    approve: (id: string) => `/api/purchase-orders/${id}/approve`,
  },
  products: {
    list: '/api/products',
    detail: (id: string) => `/api/products/${id}`,
    create: '/api/products',
    update: (id: string) => `/api/products/${id}`,
    delete: (id: string) => `/api/products/${id}`,
    adjustStock: (id: string) => `/api/products/${id}/adjust-stock`,
    movements: (id: string) => `/api/products/${id}/movements`,
    lowStock: '/api/products/low-stock',
  },
  payments: {
    list: '/api/payments',
    detail: (id: string) => `/api/payments/${id}`,
    create: '/api/payments',
    verify: (id: string) => `/api/payments/${id}/verify`,
    invoice: (id: string) => `/api/payments/${id}/invoice`,
  },
  dashboard: {
    stats: '/api/dashboard/stats',
    revenue: '/api/dashboard/revenue',
    activities: '/api/dashboard/activities',
    reports: '/api/reports/generate',
    exportReport: '/api/reports/export',
  },
  documents: {
    list: '/api/documents',
    detail: (id: string) => `/api/documents/${id}`,
    upload: '/api/documents/upload',
    delete: (id: string) => `/api/documents/${id}`,
    share: (id: string) => `/api/documents/${id}/share`,
  },
  email: {
    templates: '/api/email/templates',
    createTemplate: '/api/email/templates',
    send: '/api/email/send',
    sendBulk: '/api/email/send-bulk',
    logs: '/api/email/logs',
  },
  batch: {
    jobs: '/api/batch/jobs',
    create: '/api/batch/jobs',
    trigger: (id: string) => `/api/batch/jobs/${id}/trigger`,
    history: (id: string) => `/api/batch/jobs/${id}/history`,
  },
  iot: {
    devices: '/api/iot/devices',
    register: '/api/iot/devices',
    location: (id: string) => `/api/iot/devices/${id}/location`,
    history: (id: string) => `/api/iot/devices/${id}/history`,
    sensors: (id: string) => `/api/iot/devices/${id}/sensors`,
  },
  wos: {
    orders: '/api/wos/orders',
    detail: (id: string) => `/api/wos/orders/${id}`,
    create: '/api/wos/orders',
    status: (id: string) => `/api/wos/orders/${id}/status`,
    cancel: (id: string) => `/api/wos/orders/${id}/cancel`,
  },
};
