export const ROUTE_PERMISSIONS: Record<string, string> = {
  '/dashboard': 'dashboard.view',
  '/customers': 'customer.view',
  '/customers/create': 'customer.create',
  '/quotations': 'quotation.view',
  '/quotations/create': 'quotation.create',
  '/purchase-orders': 'purchase_order.view',
  '/purchase-orders/create': 'purchase_order.create',
  '/products': 'inventory.view',
  '/products/create': 'inventory.create',
  '/payments': 'payment.view',
  '/documents': 'document.view',
  '/email/templates': 'email.view',
  '/email/compose': 'email.create',
  '/batch/jobs': 'batch.view',
  '/iot/devices': 'iot.view',
  '/wos/orders': 'wos.view',
  '/jobs': 'job_card.view',
  '/users': 'user.view',
  '/users/create': 'user.create',
  '/roles': 'role.view',
  '/roles/create': 'role.create',
};
